"""Compatibility exports for residual static sparse solver helpers."""

from __future__ import annotations

from seis_statics.residual.solver import (
    ResidualStaticAugmentedSystem,
    ResidualStaticGauge,
    ResidualStaticLeastSquaresResult,
    ResidualStaticLsmrDiagnostics,
    ResidualStaticLsmrOptions,
    ResidualStaticMinimumDataSummary,
    ResidualStaticObservationGraphSummary,
    ResidualStaticRawLsmrResult,
    ResidualStaticStabilizationOptions,
    ResidualStaticStabilizedLeastSquaresResult,
    build_csr_matrix_from_residual_static_triplets,
    build_delay_damping_rows,
    build_residual_static_observation_graph_summary,
    build_stabilized_residual_static_augmented_system,
    build_zero_mean_gauge_rows,
    run_sparse_lsmr,
    solve_residual_static_least_squares,
    solve_residual_static_stabilized_least_squares,
    stabilization_options_from_request_solver,
    validate_lsmr_options,
    validate_minimum_residual_static_data,
    validate_residual_static_estimated_delay_limit,
    validate_residual_static_stabilization_options,
    validate_residual_static_used_mask,
)


__all__ = [
    'ResidualStaticAugmentedSystem',
    'ResidualStaticGauge',
    'ResidualStaticLeastSquaresResult',
    'ResidualStaticLsmrDiagnostics',
    'ResidualStaticLsmrOptions',
    'ResidualStaticMinimumDataSummary',
    'ResidualStaticObservationGraphSummary',
    'ResidualStaticRawLsmrResult',
    'ResidualStaticStabilizationOptions',
    'ResidualStaticStabilizedLeastSquaresResult',
    'build_delay_damping_rows',
    'build_csr_matrix_from_residual_static_triplets',
    'build_residual_static_observation_graph_summary',
    'build_stabilized_residual_static_augmented_system',
    'build_zero_mean_gauge_rows',
    'run_sparse_lsmr',
    'solve_residual_static_least_squares',
    'solve_residual_static_stabilized_least_squares',
    'stabilization_options_from_request_solver',
    'validate_minimum_residual_static_data',
    'validate_lsmr_options',
    'validate_residual_static_estimated_delay_limit',
    'validate_residual_static_stabilization_options',
    'validate_residual_static_used_mask',
]
