# Python version target
target-version = "py310"

# Ruff は "check only"。Black が唯一のフォーマッタ
fix = false
respect-gitignore = true

[pylint]
# 参照用（PLR系は選択していないので実際のチェックには影響しません）
max-statements = 80

[lint]
# Agents.md の方針に合わせて E と F のみ
select = ["E", "F"]

# Black と衝突するものは必ず無視
ignore = [
  "E203", # slice の前の空白（Blackと流儀が違う）
  "E501", # 行長（行折りはBlackに任せる）
]

# テストは現実的に緩める
[per-file-ignores]
"app/tests/**" = [
  "INP001", # __init__.py 不要
  "S101", "SLF001",
  "ARG001", "ARG002", "ARG005",
  "PLR2004", "PT011", "PT018",
]
