"""Pydantic models for describing pipeline operations."""

from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

TransformName = Literal['bandpass', 'denoise']
AnalyzerName = Literal['fbpick']


class BandpassParams(BaseModel):
    """Parameters for the band-pass filter."""

    low_hz: float = Field(..., ge=0.0)
    high_hz: float = Field(..., ge=0.0)
    taper: float = Field(0.0, ge=0.0)

    @model_validator(mode='before')
    @classmethod
    def _ensure_no_dt(cls, data: Any) -> Any:
        if isinstance(data, dict) and 'dt' in data:
            raise ValueError(
                'dt is derived from the data and can no longer be specified'
            )
        return data

    @model_validator(mode='after')
    def _check_bounds(self) -> 'BandpassParams':
        # フィールド制約（ge/gt）は Field で既に検証済み。
        if self.low_hz >= self.high_hz:
            raise ValueError('low_hz must be less than high_hz')
        return self


class PipelineOp(BaseModel):
    """Specification for a single pipeline operation."""

    kind: Literal['transform', 'analyzer']
    name: TransformName | AnalyzerName
    params: dict[str, Any] = Field(default_factory=dict)
    label: str | None = None

    @model_validator(mode='after')
    def _validate_params(self) -> 'PipelineOp':
        # name に応じて params をサブモデルで検証
        if self.name == 'bandpass':
            BandpassParams(**(self.params or {}))
        return self


class PipelineSpec(BaseModel):
    """Sequence of pipeline operations."""

    steps: list[PipelineOp]


class PipelineSectionResponse(BaseModel):
    """Response model for ``/pipeline/section``."""

    taps: dict[str, Any]
    pipeline_key: str


class PipelineAllResponse(BaseModel):
    """Response model for ``/pipeline/all``."""

    job_id: str
    state: str


class PipelineJobStatusResponse(BaseModel):
    """Response model for pipeline job status."""

    state: str
    progress: float
    message: str


class SnapOptions(BaseModel):
    """Configuration for optional raw-waveform snap refinement."""

    enabled: bool = False
    mode: Literal['peak', 'trough', 'rise'] = 'peak'
    refine: Literal['none', 'parabolic', 'zc'] = 'parabolic'
    window_ms: float = 20.0


class PickOptions(BaseModel):
    """Configuration for predicted-pick generation from probability maps."""

    method: Literal['expectation', 'argmax'] = 'expectation'
    subsample: bool = False
    sigma_ms_max: float | None = None
    snap: SnapOptions = Field(default_factory=SnapOptions)


class BatchApplyRequest(BaseModel):
    """Request model for ``/batch/apply``."""

    file_id: str
    key1_byte: int = 189
    key2_byte: int = 193
    pipeline_spec: PipelineSpec
    pick_options: PickOptions = Field(default_factory=PickOptions)
    save_picks: bool = False


class BatchApplyResponse(BaseModel):
    """Response model for creating a batch apply job."""

    job_id: str
    state: str


class BatchJobStatusResponse(BaseModel):
    """Response model for batch job status."""

    state: str
    progress: float
    message: str


class BatchJobFile(BaseModel):
    """One file entry generated by a batch job."""

    name: str
    size_bytes: int


class BatchJobFilesResponse(BaseModel):
    """Response model for batch job files listing."""

    files: list[BatchJobFile]
