"""Common contracts for static correction jobs."""

from pydantic import BaseModel


class StaticJobStatusResponse(BaseModel):
    """Response model for static correction job status."""

    state: str
    progress: float
    message: str


class StaticJobFile(BaseModel):
    """One file entry generated by a static correction job."""

    name: str
    size_bytes: int


class StaticJobFilesResponse(BaseModel):
    """Response model for static correction job files listing."""

    files: list[StaticJobFile]

