"""Residual statics model representation and design-matrix helpers."""

from __future__ import annotations

from seis_statics.residual.design_matrix import (
    ResidualStaticColumnLayout,
    ResidualStaticModelEvaluation,
    ResidualStaticObservationMatrixTriplets,
    ResidualStaticParameterParts,
    build_residual_static_column_layout,
    build_residual_static_observation_matrix_triplets,
    compute_linear_abs_offset_moveout_s,
    evaluate_residual_static_model,
    pack_residual_static_parameters,
    unpack_residual_static_parameters,
)
from seis_statics.residual.robust import (
    ROBUST_SCALE_FLOOR_S,
    ResidualStaticRobustIterationSummary,
    ResidualStaticRobustMethod,
    ResidualStaticRobustOptions,
    ResidualStaticRobustSolveResult,
    ResidualStaticRobustStopReason,
    build_residual_static_outlier_mask,
    compute_residual_static_robust_center_scale,
    robust_options_from_request_robust,
    solve_residual_static_robust_least_squares,
    validate_residual_static_robust_options,
)
from seis_statics.residual.solver import (
    ResidualStaticAugmentedSystem,
    ResidualStaticGauge,
    ResidualStaticLeastSquaresResult,
    ResidualStaticLsmrDiagnostics,
    ResidualStaticLsmrOptions,
    ResidualStaticMinimumDataSummary,
    ResidualStaticObservationGraphSummary,
    ResidualStaticRawLsmrResult,
    ResidualStaticStabilizationOptions,
    ResidualStaticStabilizedLeastSquaresResult,
    build_csr_matrix_from_residual_static_triplets,
    build_delay_damping_rows,
    build_residual_static_observation_graph_summary,
    build_stabilized_residual_static_augmented_system,
    build_zero_mean_gauge_rows,
    run_sparse_lsmr,
    solve_residual_static_least_squares,
    solve_residual_static_stabilized_least_squares,
    stabilization_options_from_request_solver,
    validate_lsmr_options,
    validate_minimum_residual_static_data,
    validate_residual_static_estimated_delay_limit,
    validate_residual_static_stabilization_options,
    validate_residual_static_used_mask,
)
from seis_statics.residual.types import MoveoutModel, ResidualStaticSolverInputs


__all__ = [
    'MoveoutModel',
    'ROBUST_SCALE_FLOOR_S',
    'ResidualStaticAugmentedSystem',
    'ResidualStaticColumnLayout',
    'ResidualStaticGauge',
    'ResidualStaticLeastSquaresResult',
    'ResidualStaticLsmrDiagnostics',
    'ResidualStaticLsmrOptions',
    'ResidualStaticMinimumDataSummary',
    'ResidualStaticModelEvaluation',
    'ResidualStaticObservationMatrixTriplets',
    'ResidualStaticObservationGraphSummary',
    'ResidualStaticParameterParts',
    'ResidualStaticRawLsmrResult',
    'ResidualStaticRobustIterationSummary',
    'ResidualStaticRobustMethod',
    'ResidualStaticRobustOptions',
    'ResidualStaticRobustSolveResult',
    'ResidualStaticRobustStopReason',
    'ResidualStaticStabilizationOptions',
    'ResidualStaticStabilizedLeastSquaresResult',
    'ResidualStaticSolverInputs',
    'build_csr_matrix_from_residual_static_triplets',
    'build_delay_damping_rows',
    'build_residual_static_column_layout',
    'build_residual_static_observation_matrix_triplets',
    'build_residual_static_observation_graph_summary',
    'build_residual_static_outlier_mask',
    'build_stabilized_residual_static_augmented_system',
    'build_zero_mean_gauge_rows',
    'compute_linear_abs_offset_moveout_s',
    'compute_residual_static_robust_center_scale',
    'evaluate_residual_static_model',
    'pack_residual_static_parameters',
    'run_sparse_lsmr',
    'robust_options_from_request_robust',
    'solve_residual_static_robust_least_squares',
    'solve_residual_static_least_squares',
    'solve_residual_static_stabilized_least_squares',
    'stabilization_options_from_request_solver',
    'unpack_residual_static_parameters',
    'validate_lsmr_options',
    'validate_minimum_residual_static_data',
    'validate_residual_static_estimated_delay_limit',
    'validate_residual_static_robust_options',
    'validate_residual_static_stabilization_options',
    'validate_residual_static_used_mask',
]
