"""Contracts for batch pipeline application jobs."""

from typing import Literal

from pydantic import BaseModel, Field

from app.contracts.pipeline import PipelineSpec


class SnapOptions(BaseModel):
    """Configuration for optional raw-waveform snap refinement."""

    enabled: bool = False
    mode: Literal['peak', 'trough', 'rise'] = 'peak'
    refine: Literal['none', 'parabolic', 'zc'] = 'parabolic'
    window_ms: float = 20.0


class PickOptions(BaseModel):
    """Configuration for predicted-pick generation from probability maps."""

    method: Literal['expectation', 'argmax'] = 'expectation'
    subsample: bool = False
    sigma_ms_max: float | None = None
    snap: SnapOptions = Field(default_factory=SnapOptions)


class BatchApplyRequest(BaseModel):
    """Request model for ``/batch/apply``."""

    file_id: str
    key1_byte: int = 189
    key2_byte: int = 193
    pipeline_spec: PipelineSpec
    pick_options: PickOptions = Field(default_factory=PickOptions)
    save_picks: bool = False


class BatchApplyResponse(BaseModel):
    """Response model for creating a batch apply job."""

    job_id: str
    state: str


class BatchJobStatusResponse(BaseModel):
    """Response model for batch job status."""

    state: str
    progress: float
    message: str


class BatchJobFile(BaseModel):
    """One file entry generated by a batch job."""

    name: str
    size_bytes: int


class BatchJobFilesResponse(BaseModel):
    """Response model for batch job files listing."""

    files: list[BatchJobFile]
